const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { execFileSync, spawnSync } = require('node:child_process');
const { validateSlither, validateBountyGate } = require('../dist/validation/input');
const { applyReviews } = require('../dist/review/reviews');
const { readSourceWindow } = require('../dist/source/readSourceWindow');
const { compareReports } = require('../dist/report/compareReports');
const { loadSuppressions } = require('../dist/suppressions/suppressions');
const cli = path.resolve('dist/cli.js');
function run(args, expected = 0) {
  const result = spawnSync(process.execPath, [cli, ...args], { encoding: 'utf8' });
  assert.equal(result.status, expected, result.stderr);
  return result;
}
(async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'aevasec-workflow-'));
  try {
    const target = path.join(root, 'target');
    const out = path.join(root, 'out');
    await fs.mkdir(target);
    execFileSync('git', ['init', '-q', target]);
    await fs.writeFile(path.join(target, 'Vault.sol'), 'contract Vault {}\n');
    execFileSync('git', ['-C', target, 'add', 'Vault.sol']);
    execFileSync('git', ['-C', target, '-c', 'user.name=Test', '-c', 'user.email=test@example.invalid', 'commit', '-qm', 'fixture']);
    const args = ['ingest', 'slither', path.resolve('fixtures/slither-sample.json'), '--target', target, '--out', out];
    run(args);
    const reportPath = path.join(out, 'report.json');
    const initial = JSON.parse(await fs.readFile(reportPath, 'utf8'));
    assert.match(initial.target.gitCommit, /^[a-f0-9]{40}$/);
    assert.match(initial.engines[0].inputSha256, /^[a-f0-9]{64}$/);
    assert.equal(initial.target.dirty, false);
    const first = initial.findings[0];
    run(['review', reportPath, first.id, 'NEEDS_CONTEXT', '--notes', 'Check caller path', '--poc', 'notes/poc.sol']);
    run(args);
    const reviewed = JSON.parse(await fs.readFile(reportPath, 'utf8'));
    assert.equal(reviewed.findings[0].triage.review.notes, 'Check caller path');
    assert.equal(reviewed.findings[0].triage.review.pocReference, 'notes/poc.sol');
    const reviews = JSON.parse(await fs.readFile(path.join(target, '.aevasec/reviews.json'), 'utf8'));
    assert.equal(applyReviews(initial.findings, reviews.items, 'different-commit')[0].triage.review, undefined);
    await fs.writeFile(path.join(target, '.aevasec/suppressions.json'), JSON.stringify({ schemaVersion: '1.0', items: [{ ruleId: first.ruleId, fingerprint: first.fingerprint.value, reason: 'Reviewed fixture' }] }));
    await fs.copyFile(reportPath, path.join(root, 'previous.json'));
    await fs.writeFile(path.join(out, 'packets', 'personal-notes.md'), 'keep');
    run([...args, '--previous', path.join(root, 'previous.json')]);
    const latest = JSON.parse(await fs.readFile(reportPath, 'utf8'));
    assert.equal(latest.stats.suppressedFindings, 1);
    assert.equal(latest.comparison.unchanged.length, 3);
    await assert.rejects(fs.access(path.join(out, 'packets', `${first.id}.md`)));
    assert.equal(await fs.readFile(path.join(out, 'packets', 'personal-notes.md'), 'utf8'), 'keep');
    const changed = { ...initial, findings: [{ ...first, fingerprint: { ...first.fingerprint, value: 'changed' } }] };
    assert.equal(compareReports(initial, changed).added.length, 1);
    assert.equal(compareReports(initial, changed).unchanged.length, 0);
    const outside = path.join(root, 'Outside.sol');
    await fs.writeFile(outside, 'secret source');
    await fs.symlink(outside, path.join(target, 'Link.sol'));
    assert.equal((await readSourceWindow({ targetPath: target, relativeFile: 'Link.sol', lineStart: 1 })).available, false);
    assert.equal((await readSourceWindow({ targetPath: target, relativeFile: 'Vault.sol', lineStart: 100 })).available, false);
    await fs.writeFile(path.join(target, '.aevasec/suppressions.json'), JSON.stringify({ schemaVersion: '1.0', items: [{ ruleId: first.ruleId, fingerprint: first.fingerprint.value, reason: 'bad expiry', expiresAt: 'invalid' }] }));
    await assert.rejects(loadSuppressions(target), /expiry/);
    await fs.writeFile(path.join(target, '.aevasec/suppressions.json'), JSON.stringify({ schemaVersion: '1.0', items: [] }));
    const bad = path.join(root, 'bad.json');
    await fs.writeFile(bad, '{"success":true,"results":{"detectors":[{}]}}');
    assert.match(run(['ingest', 'slither', bad, '--target', target, '--out', out], 1).stderr, /Invalid Slither detector/);
    assert.match(run([...args, '--bounty', path.join(root, 'missing.json')], 1).stderr, /Bounty gate not found/);
    await fs.writeFile(path.join(target, 'Vault.sol'), 'contract Changed {}');
    assert.match(run(['review', reportPath, first.id, 'NEEDS_CONTEXT', '--notes', 'changed'], 1).stderr, /tracked modifications/);
    assert.throws(() => validateBountyGate({ schemaVersion: '1.0', minimumPaidSeverity: 'INVALID' }), /minimumPaidSeverity/);
    assert.throws(() => validateSlither({ success: true, results: { detectors: [{ check: 'x', impact: 'High', confidence: 'High', description: 'x', elements: [{ source_mapping: { lines: [-1] } }] }] } }), /source mapping/);
    console.log('CLI review, provenance, validation, comparison and stale-packet regressions passed');
  } finally { await fs.rm(root, { recursive: true, force: true }); }
})().catch(error => { console.error(error); process.exitCode = 1; });
