// Builds a judged-findings fixture from a Code4rena report.md and a built contest checkout.
// Usage: node scripts/buildJudgedFixture.js <target-dir> <report.md> <contest-slug> <contest-name> > fixture.json
// IDs and titles come from the report headings. Locations are the functions enclosing the
// source lines each finding links to. Findings with no source link are left with empty
// locations and "needsManualLocation": true for a reviewer to fill in from the prose.
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const [target, reportPath, slug, name] = process.argv.slice(2);
if (!target || !reportPath || !slug || !name) { console.error('Usage: node scripts/buildJudgedFixture.js <target-dir> <report.md> <contest-slug> <contest-name>'); process.exit(1); }

function loadFunctions() {
  const toml = fs.existsSync(path.join(target, 'foundry.toml')) ? fs.readFileSync(path.join(target, 'foundry.toml'), 'utf8') : '';
  const dir = path.join(target, /^\s*out\s*=\s*['"]([^'"]+)['"]/m.exec(toml)?.[1] ?? 'out', 'build-info');
  const files = fs.readdirSync(dir).filter(file => file.endsWith('.json')).map(file => path.join(dir, file)).sort((a, b) => fs.statSync(a).mtimeMs - fs.statSync(b).mtimeMs);
  const bySource = new Map();
  for (const file of files) {
    const info = JSON.parse(fs.readFileSync(file, 'utf8'));
    for (const [source, value] of Object.entries(info.output?.sources ?? {})) {
      const content = info.input?.sources?.[source]?.content;
      if (!value.ast || content === undefined) continue;
      const bytes = Buffer.from(content, 'utf8');
      const lineAt = offset => { let line = 1; for (let i = 0; i < offset && i < bytes.length; i += 1) if (bytes[i] === 10) line += 1; return line; };
      const functions = [];
      const visit = (node, contract) => {
        if (node.nodeType === 'FunctionDefinition' || node.nodeType === 'ModifierDefinition') {
          const [start, length] = node.src.split(':').map(Number);
          functions.push({ contract, function: node.name || node.kind, visibility: node.visibility ?? 'modifier', lineStart: lineAt(start), lineEnd: lineAt(start + length) });
          return;
        }
        for (const child of node.nodes ?? []) visit(child, node.nodeType === 'ContractDefinition' ? node.name : contract);
      };
      visit(value.ast, null);
      bySource.set(source.replace(/\\/g, '/'), functions);
    }
  }
  return bySource;
}

const functionsBySource = loadFunctions();
const report = fs.readFileSync(reportPath, 'utf8');
// A finding section ends at the next finding or at the next top-level heading.
const sections = report.split(/^(?=## \[\[[HM]-\d+\]|# )/m).filter(section => /^## \[\[[HM]-\d+\]/.test(section));
const refs = new Set();
const findings = sections.map(section => {
  const heading = /^## \[\[([HM]-\d+)\]\s*(.*?)\]\((https?:[^)]+)\)/.exec(section);
  if (!heading) throw new Error(`Unparsed heading: ${section.slice(0, 80)}`);
  const locations = new Map();
  const unresolved = new Set();
  for (const match of section.matchAll(new RegExp(`${slug}/blob/([^/]+)/([^#)\\s>]+\\.sol)#L(\\d+)`, 'g'))) {
    refs.add(match[1]);
    const file = match[2];
    const line = Number(match[3]);
    const fn = (functionsBySource.get(file) ?? []).find(item => line >= item.lineStart && line <= item.lineEnd);
    if (!fn) { unresolved.add(`${file}:${line}`); continue; }
    const key = `${file}:${fn.lineStart}`;
    locations.set(key, { file, ...fn, links: (locations.get(key)?.links ?? 0) + 1 });
  }
  return {
    id: heading[1],
    title: heading[2].replace(/`/g, '').replace(/\\([_*])/g, '$1').replace(/\.$/, ''),
    url: heading[3],
    locations: [...locations.values()],
    ...(unresolved.size ? { linksOutsideFunctions: [...unresolved] } : {}),
    ...(locations.size === 0 ? { needsManualLocation: true } : {})
  };
});

process.stdout.write(`${JSON.stringify({
  schemaVersion: '1.1',
  contest: name,
  repository: `https://github.com/code-423n4/${slug}`,
  commit: execFileSync('git', ['-C', target, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(),
  source: `https://github.com/code-423n4/${slug}-findings/blob/main/report.md`,
  reportLinkRefs: [...refs],
  provenance: 'Generated by scripts/buildJudgedFixture.js from the primary report: IDs and titles from headings, locations from the functions enclosing each linked source line. Entries marked locationSource "prose" were filled in by a reviewer from the report text. detectorRootCause labels are one reviewer\'s judgement: a lead counts only when the detector text states the judged root cause.',
  findings
}, null, 2)}\n`);
